export {default as MyInfo} from "./MyInfo"
export {default as MyEdu} from "./MyEdu"
export {default as MyPro} from "./MyPro"
export {default as MyHob} from "./MyHob"
export {default as Home} from "./Home"
export {default as Comment} from "./Comment"
